# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Node.js package updates
  - package-ecosystem: "npm"
    directory: "/crud-node-express" # Location of package.json
    schedule:
      interval: "daily" # Check for updates daily
    commit-message:
      prefix: "fix" # Commit message prefix
    open-pull-requests-limit: 5 # Limit the number of open PRs to 5
    ignore:
      - dependency-name: "some-deprecated-package" # Example of ignoring a package

  # Docker image updates
  - package-ecosystem: "docker"
    directory: "/" # Location of your Dockerfile
    schedule:
      interval: "daily" # Check for updates daily
    commit-message:
      prefix: "fix" # Commit message prefix
    open-pull-requests-limit: 5 # Limit the number of open PRs to 5
