version: "3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    image: ihusnianali/node-crud-app
    ports:
      - 3000:3000
    environment:
      APP_NAME: LearnDocker
      PORT: 3000
      DB_USER: mongo
      DB_PASSWORD: password
      DB_NAME_IP: mongo_db
      DB_PORT: 27017
      DB_NAME: node-crud-app
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}