name: Node.js Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd crud-node-express  # Change to the correct directory
          npm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd crud-node-express
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-crud-app:latest .

      - name: Docker Image Tag
        run: |
          cd crud-node-express
          docker tag node-crud-app:latest ${{ secrets.DOCKER_USERNAME }}/node-crud-app:latest

      - name: Push Docker image to Docker Hub
        run: |
          cd crud-node-express
          docker push ${{ secrets.DOCKER_USERNAME }}/node-crud-app:latest
